export const MyCertificationEn = [
    {
      id: 1,
      name: "FrontEnd Developer",
      institute: "Laboratoria",
      date: "September 2023",
      type: "FrontEnd Developer",
    },
    {
      id: 2,
      name: "Professional React Course",
      institute: "Codigo Facilito",
      date: "agosto 2023",
      type: "Development Tools",
    },
    {
      id: 3,
      name: "Scrum",
      institute: "CertiIProf SFPC",
      date: "agosto 2023",
      type: "Others",
    },
    {
      id: 4,
      name: "Scrum for Software Development Projects",
      institute: "SENA",
      date: "September 2023",
      type: "Others",
    },
    {
      id: 5,
      name: "Effective communication/ Key about autonomy",
      institute: "Globant University",
      date: "October2023",
      type: "SoftSkill",
    },
    {
      id: 6,
      name: "Introduction to Backend Development",
      institute: "Platzi",
      date: "October2023",
      type: "Development Tools",
    },
    {
      id: 7,
      name: "Artificial Intelligence Program",
      institute: "Tallen Fest Latam",
      date: "October2023",
      type: "Development Tools",
    },
    {
      id: 8,
      name: "Scrum",
      institute: "Globant University",
      date: "November 2023",
      type: "Others",
    },
    {
        id: 9,
        name: "Hackathon Laboratoria Talent Fest LATAM 2023",
        institute: "Laboratoria",
        date: "November 2023",
        type: "Development Tools",
      },
      {
        id: 10,
        name: "1st Place Hackathon at Laboratoria Talent Fest LATAM 2023",
        institute: "Laboratoria",
        date: "November 2023",
        type: "Awards",
      },
      {
        id: 11,
        name: "Reflection and Self-awareness",
        institute: "Laboratoria",
        date: "September 2023",
        type: "Awards",
      }
  ];
  